Importing NumPy

In [2]:
import numpy as np

Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
# Dimensions?

a.ndim

1

In [6]:
# Shape?

b.shape

(2, 3)

In [7]:
# Datatype?

a.dtype

dtype('int64')

In [9]:
# Size? (in Bytes)

a.itemsize

8

In [15]:
# Specifying type

x = np.array([2,3,4], dtype='int16')

In [16]:
x.dtype

dtype('int16')

In [14]:
x.itemsize

2

In [20]:
# Total Size?

x.size * x.itemsize

6

In [22]:
# Another way

x.nbytes

6

In [23]:
b.itemsize

8

Slicing numpy arrays

In [24]:
d = np.array([[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20]])
print(d)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [27]:
# Get an element (as [row, column])

print(d[1,8]) # from the start
print(d[1,-2]) # from the end

19
19


In [46]:
# Get a row

print(d[0, :], end = '\n') # 1st row 
print(d[1, :]) # 2nd row

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [39]:
d[0, :]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# Get specific column

print(d[:, 0], end = '\n')
print(d[:, 1])

[ 1 11]
[ 2 12]


In [42]:
d[:, 0]

array([ 1, 11])

In [49]:
# Rows and columns can be accessed from the back too

print("----| Rows |----")
print(d[-2, :], end = '\n') # 1st row 
print(d[-1, :]) # 2nd row
print('\n----| Columns |----')
print(d[:, -10], end = '\n')
print(d[:, -9])

----Rows----
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]

----Columns----
[ 1 11]
[ 2 12]


In [64]:
# Starting and ending from specific indices with steps
# Syntax for 1D arrays --> array[startIndex: endIndex: step] 
# Syntax for 2D arrays --> array[rowIndex, startIndex: endIndex: step] 

print("----| Print Indices 0,2 from 1st Row |----")
print(d[0, 0:4:2]) # will print indices 0,2
print("\n----| Print Indices 0,2,4,6,8 from 2nd Row |----")
print(d[1, 0:10:2]) # will print indices 0,2,4,6,8

# Stop index('stopIndex element') is always excluded



----| Print Indices 0,2 from 1st Row |----
[1 3]

----| Print Indices 0,2,4,6,8 from 2nd Row |----
[11 13 15 17 19]


In [68]:
# Negative indexing works only when for :-
# positive stepping startIndex < endIndex i.e, d[0, 0:-1:1]
# negative stepping endIndex < startIndex i.e, d[0, -1:0:-1]

print(d[0, 0:-1:1], '\n')

print(d[0, -10:-1:1], '\n')

print(d[0, -1:0:-1], '\n')

print(d[0, -1:-10:-1])

[1 2 3 4 5 6 7 8 9] 

[1 2 3 4 5 6 7 8 9] 

[10  9  8  7  6  5  4  3  2] 

[10  9  8  7  6  5  4  3  2]


In [79]:
# Changing/updating an element

# at a specific position
d[0,0] = 100
print(d[0], '\n')
print(d)

[100 404 404 404 404 404 404 404 404 404] 

[[100 404 404 404 404 404 404 404 404 404]
 [ 11 123  13  14  15  16  17  18  19  20]]


In [80]:
# an entire column with same element
d[:,1] = 123
print(d[:,1], '\n')
print(d)

[123 123] 

[[100 123 404 404 404 404 404 404 404 404]
 [ 11 123  13  14  15  16  17  18  19  20]]


In [81]:
# an entire row with same element
d[0,:] = 404
print(d[0,:], '\n')
print(d)

[404 404 404 404 404 404 404 404 404 404] 

[[404 404 404 404 404 404 404 404 404 404]
 [ 11 123  13  14  15  16  17  18  19  20]]


In [88]:
# updating column with different elements
d[:,0] = [1,2]
print(d[:,0], '\n')
print(d)


[1 2] 

[[  1 404 404 404 404 404 404 404 404 404]
 [  2 123  13  14  15  16  17  18  19  20]]


In [89]:
# updating column with different elements
d[0,:] = [100,200,300,400,500,600,700,800,900,1000]
print(d[0,:], '\n')
print(d)

[ 100  200  300  400  500  600  700  800  900 1000] 

[[ 100  200  300  400  500  600  700  800  900 1000]
 [   2  123   13   14   15   16   17   18   19   20]]
