Importing NumPy

In [2]:
import numpy as np

Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
# Dimensions?

a.ndim

1

In [6]:
# Shape?

b.shape

(2, 3)

In [7]:
# Datatype?

a.dtype

dtype('int64')

In [8]:
# Size? (in Bytes)

a.itemsize

8

In [9]:
# Specifying type

x = np.array([2,3,4], dtype='int16')

In [10]:
x.dtype

dtype('int16')

In [11]:
x.itemsize

2

In [12]:
# Total Size?

x.size * x.itemsize

6

In [13]:
# Another way

x.nbytes

6

In [14]:
b.itemsize

8

Slicing numpy arrays

In [15]:
d = np.array([[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20]])
print(d)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [16]:
# Get an element (as [row, column])

print(d[1,8]) # from the start
print(d[1,-2]) # from the end

19
19


In [17]:
# Get a row

print(d[0, :], end = '\n') # 1st row 
print(d[1, :]) # 2nd row

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [18]:
d[0, :]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# Get specific column

print(d[:, 0], end = '\n')
print(d[:, 1])

[ 1 11]
[ 2 12]


In [20]:
d[:, 0]

array([ 1, 11])

In [21]:
# Rows and columns can be accessed from the back too

print("----| Rows |----")
print(d[-2, :], end = '\n') # 1st row 
print(d[-1, :]) # 2nd row
print('\n----| Columns |----')
print(d[:, -10], end = '\n')
print(d[:, -9])

----| Rows |----
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]

----| Columns |----
[ 1 11]
[ 2 12]


In [22]:
# Starting and ending from specific indices with steps
# Syntax for 1D arrays --> array[startIndex: endIndex: step] 
# Syntax for 2D arrays --> array[rowIndex, startIndex: endIndex: step] 

print("----| Print Indices 0,2 from 1st Row |----")
print(d[0, 0:4:2]) # will print indices 0,2
print("\n----| Print Indices 0,2,4,6,8 from 2nd Row |----")
print(d[1, 0:10:2]) # will print indices 0,2,4,6,8

# Stop index('stopIndex element') is always excluded



----| Print Indices 0,2 from 1st Row |----
[1 3]

----| Print Indices 0,2,4,6,8 from 2nd Row |----
[11 13 15 17 19]


In [23]:
# Negative indexing works only when for :-
# positive stepping startIndex < endIndex i.e, d[0, 0:-1:1]
# negative stepping endIndex < startIndex i.e, d[0, -1:0:-1]

print(d[0, 0:-1:1], '\n')

print(d[0, -10:-1:1], '\n')

print(d[0, -1:0:-1], '\n')

print(d[0, -1:-10:-1])

[1 2 3 4 5 6 7 8 9] 

[1 2 3 4 5 6 7 8 9] 

[10  9  8  7  6  5  4  3  2] 

[10  9  8  7  6  5  4  3  2]


In [24]:
# Changing/updating an element

# at a specific position
d[0,0] = 100
print(d[0], '\n')
print(d)

[100   2   3   4   5   6   7   8   9  10] 

[[100   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]]


In [25]:
# an entire column with same element
d[:,1] = 123
print(d[:,1], '\n')
print(d)

[123 123] 

[[100 123   3   4   5   6   7   8   9  10]
 [ 11 123  13  14  15  16  17  18  19  20]]


In [26]:
# an entire row with same element
d[0,:] = 404
print(d[0,:], '\n')
print(d)

[404 404 404 404 404 404 404 404 404 404] 

[[404 404 404 404 404 404 404 404 404 404]
 [ 11 123  13  14  15  16  17  18  19  20]]


In [27]:
# updating column with different elements
d[:,0] = [1,2]
print(d[:,0], '\n')
print(d)


[1 2] 

[[  1 404 404 404 404 404 404 404 404 404]
 [  2 123  13  14  15  16  17  18  19  20]]


In [28]:
# updating column with different elements
d[0,:] = [100,200,300,400,500,600,700,800,900,1000]
print(d[0,:], '\n')
print(d)

[ 100  200  300  400  500  600  700  800  900 1000] 

[[ 100  200  300  400  500  600  700  800  900 1000]
 [   2  123   13   14   15   16   17   18   19   20]]


In [29]:
e = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
e[0,1,1]

4

In [35]:
# replace 
e[:,1,:] = [[0,0],[100,100]]
e

array([[[  1,   2],
        [  0,   0]],

       [[  5,   6],
        [100, 100]]])

Different Types of arrays

In [39]:
# all 0s
np.zeros((3,3), dtype='int16') # you can also specify dtype

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [38]:
# all 1s
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
# a specific number
np.full((5,5), 101)

array([[101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101]])

or

In [44]:
np.full(b.shape, 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [45]:
# using full_like (to use other matrix as reference)
np.full_like(d, 7)

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [46]:
# random decimal numbers
np.random.rand(4,2)

array([[0.54961387, 0.54330648],
       [0.31338049, 0.53886179],
       [0.08334   , 0.77415495],
       [0.77878724, 0.98427682]])

In [50]:
# random integer values
np.random.randint(4,6, size=(3,3))

array([[5, 5, 4],
       [4, 5, 5],
       [5, 5, 4]])

In [58]:
np.random.randint(-100,-80, size=(7,7))

array([[ -82,  -81,  -83,  -91,  -96, -100,  -86],
       [ -93,  -85,  -93,  -93,  -84,  -91,  -84],
       [ -82,  -82,  -81,  -85,  -87,  -92,  -87],
       [ -97,  -88,  -90,  -93,  -93,  -82,  -88],
       [ -83,  -82,  -93,  -86,  -82,  -91,  -95],
       [ -85,  -99,  -86,  -99,  -96,  -82,  -91],
       [ -99,  -89,  -98,  -83,  -92,  -86,  -81]])

In [53]:
np.random.random_sample(a.shape)

array([0.41332197, 0.86532816, 0.43252263])

In [59]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
# repeat an array
arr = np.array([[1,2,3]])
r = np.repeat(arr,3, axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [62]:
### let us try to print this
#[
#    [1 1 1 1 1]
#    [1 0 0 0 1]
#    [1 0 5 0 1]
#    [1 0 0 0 1]
#    [1 1 1 1 1]
#]

In [72]:
f = np.ones((5,5), dtype = 'int16')
s = np.zeros((3,3))
s[1,1] = 5
f[1:4,1:4] = s
print(f)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 5 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


If you do not use .copy() function then the array new array points to the same address as old array so changing one changes both

In [77]:
aa = np.array([1,2,3])
ab = aa
aa[1] = 100
print(ab)
ab[2] = 108
print(aa)

[  1 100   3]
[  1 100 108]


Hence, use .copy() to make a copy

In [82]:
ac = np.array([1,2,3])
ad = ac.copy()

ac[1] = 100
print(ad)

ac = np.array([1,2,3])

ad[2] = 108
print(ac)

[1 2 3]
[1 2 3]
